theme: jekyll-theme-time-machine
title: welcome, you're in the write place
description: Just the page of an improperly caffeinated research associate with a knack for knitting together verbiage. Follow for project updates!
